Add logsoftmax and fix for jax_funcify_join
pymc-devs/aesara pull request #343
Opened 2021-03-17 18:05 UTC by aseyboldt

Add a LogSoftmax implementation for `jax_funcify`.

Also, this adds a jax tensor conversion for `jax_funcify_Join`. I'm not sure this is the best solution, it might also not be needed if optimizations are used. Without this change this fails:

```python
import pymc3 as pm
import aesara.tensor as aet
import aesara
import pymc3.sampling_jax
import numpy as np

with pm.Model() as model:
    a = pm.Normal('a', shape=(13, 3, 5))
    b = pm.Normal('b', shape=(17, 5, 7))
    pm.Normal('c', mu=aet.tensordot(a, b, axes=(2, 1)), shape=(13, 3, 17, 7))

with model:
    # fails with attribute access tuple.ndim
    trace = pymc3.sampling_jax.sample_numpyro_nuts()

# this doesn't fail, the join gets optimized away I think
func = model.logp_dlogp_function(mode=aesara.compile.mode.JAX)
func.set_extra_values({})
x = np.random.randn(func.size)

%%timeit
val, grad = func(x)
jax.device_get(grad)
```
cc @brandonwillard @OriolAbril

2021-03-17 18:13 UTC, OriolAbril submitted a review, later dismissed
Looks good, do you want me to rebase and continue with this forward?

2021-03-17 18:47 UTC, brandonwillard requested changes
We need to add a test before we can merge.

2021-03-18 08:24 UTC, twiecki commented
@OriolAbril Can you take over and add a test?

2021-03-19 20:02 UTC, OriolAbril commented
@brandonwillard should I add a test for Join? It looks like there is no specific test at all for Join in test jax. If so, which cases should it cover?

2021-03-20 02:14 UTC, brandonwillard commented
> @brandonwillard should I add a test for Join? It looks like there is no specific test at all for Join in test jax. If so, which cases should it cover?

Absolutely, and especially if we don't already have a test for `Join`!

2021-03-20 03:03 UTC, OriolAbril commented
I have added some tests using matrix types along both 0 and 1 axis but I don't really have any idea about what joins should be covered by the tests

2021-03-20 17:37 UTC, merged