add _str_impl and _repr_impl to Variable
pymc-devs/aesara pull request #417
Opened 2021-05-18 09:24 UTC by Spaak

See the discussion [here](https://github.com/pymc-devs/pymc3/pull/4692#issuecomment-842969904); this PR will allow patching of `str(var)` and `repr(var)` by children/instances of `Variable` without having to dynamically patch the type.

2021-05-19 03:31 UTC, brandonwillard requested changes
What does deferring to a new `_[str|repr]_impl` method provide to `__[str|repr]__` that standard class inheritance and method overriding doesn't?  

Also, for the intended purpose of this change, a simple wrapper or proxy class would accomplish at least as much as monkey patching an instance's `_[str|repr]_impl` methods or&mdash;worse yet&mdash;`__class__`.

Regardless, before changing two fundamental built-in methods in one of Aesara's core classes, we need to establish that this additional indirection is worth adding, especially in light of all the non-invasive alternatives, like `aesara.printing`, [`reprlib`](https://docs.python.org/3.7/library/reprlib.html), [`pprint`](https://docs.python.org/3.7/library/pprint.html), [`IPython.lib.pretty`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.lib.pretty.html), etc.  (NB: all of these alternatives provide some form of dispatch to customize the format of existing classes without altering them.)

To start, does this change only serve to aid in the implementation of https://github.com/pymc-devs/pymc3/pull/4692?

2021-05-19 09:10 UTC, Spaak commented
@brandonwillard @twiecki 

> What does deferring to a new `_[str|repr]_impl` method provide to `__[str|repr]__` that standard class inheritance and method overriding doesn't?

To quote the explanation I gave in https://github.com/pymc-devs/pymc3/pull/4692:

> The (only) reason that I used this dynamic type patching is that Python's builtin `str` will always call the `__str__` that is *defined on the object's class* (see [this answer on SO](https://stackoverflow.com/questions/5918003/python-override-str-in-an-exception-instance/5918210#5918210)). If we were to do `myvar.__str__ = somefun` then still `str(myvar)` would *not* call `somefun` (unlike any other method assignment). The reason that overriding built-in `str` and `repr` (which behaves in the same way) is desireable is for console support; only that way can we get behaviour like:
> 
> ```
> >>> y
> y ~ N(f(a, b), y_sigma)
> ```
> 
> otherwise the user would have to type `>>> pretty_print(y)` or so to get the same.

The **key question** here is: do we want to provide enhanced string representations when the user simply types a variable name `y` at the console prompt, or do we always want to require `pprint(y)`? At least in the PyMC3 case, for v4, if we want nice printing for simply typing a variable name, this requires *some* change in the way `__str__` is handled.

I can see five options:
1. Patching `__class__`
2. Deferring to `_[str|repr]_impl` in Aesara `Variable.__[str|repr]__` and patching the former in PyMC3
3. Re-instating the object-oriented approach for PyMC3 `Distribution`s added to `Model`s
4. Using a wrapper around Aesara `Variable`s when creating them in PyMC3
5. Not supporting quick formatted printing on the console at all

Contra 1: potential obscure side effects, as you rightly pointed out.

To me the only option without any clear downsides is 2.

Contra 3: this would be a massive and unwanted overhaul of the approach taken with v4.

Contra 4: this would mean users no longer are dealing directly with Aesara `TensorVariable`s but with wrappers around those. Supporting the neat integration of PyMC3 objects with arbitrary Aesara math, deterministics, etc. with a wrapper class is non-trivial and would probably lead to unclear code.

Contra 5: quick formatted printing of variables on the console without having to explicitly invoke a special pretty printing function is great to have from a user experience perspective (and also very common in other widely used toolboxes).

It's important to note that the **issue here is separate** from the more general discussion of which machinery to actually use to generate the string representations: either the relatively limited functionality in my PR https://github.com/pymc-devs/pymc3/pull/4692 (essentially a recreation and refactoring of what we had in v3); or more elaborate arbitrary graph renderings as in your code from `symbolic_pymc`. No matter which of these two options we choose, we need to make a decision on whether and how to support "quick console printing".

2021-05-19 10:00 UTC, twiecki commented
I want us to support "quick console printing", it's a really pleasant surprise to users when that works out, and for `aesara` I can never remember the `pprint` import and hence rarely use it. I agree that option 2 is a reasonable work-around this Python quirk.

2021-05-19 19:17 UTC, twiecki commented
> Contra 4: this would mean users no longer are dealing directly with Aesara TensorVariables but with wrappers around those. Supporting the neat integration of PyMC3 objects with arbitrary Aesara math, deterministics, etc. with a wrapper class is non-trivial and would probably lead to unclear code.

I don't think that's necessarily the case. We could wrap but still return a `TensorVariable`, no? I think in that case that might be preferable.

2021-05-20 00:06 UTC, michaelosthege commented
Thanks for the great overview of options @Spaak!

To me option 2 sounds best too. I agree with @twiecki about option 4, but if I'm afraid of introducing a lot of type clutter. 
Option 2 would also be implemented very close to the RandomVariable Ops, right?

2021-05-20 06:02 UTC, brandonwillard commented
> To quote the explanation I gave in
[pymc-devs/pymc3#4692](https://github.com/pymc-devs/pymc3/pull/4692):

So I can assume your response is essentially a positive answer to my question:

> To start, does this change only serve to aid in the implementation of
[pymc-devs/pymc3#4692](https://github.com/pymc-devs/pymc3/pull/4692)?

Again, since this `_[str|repr]_impl` indirection serves no apparent purpose for *this* library, it's hard to justify adding it.

> The **key question** here is: do we want to provide enhanced string representations when the user simply types a variable name `y` at the console prompt, or do we always want to require `pprint(y)`?

Actually, the key question is: **do we want to make a change to a core class that serves no purpose other than to allow pretty printing via `__[str|repr]__` in non-IPython/Jupyter consoles for certain `Variable` instances in certain situations via monkey patching**.  The answer is "No".

I'll attempt to clarify in the following.

## Unaddressed concerns

The added convenience of console-based pretty printing is minor&mdash;at best&mdash;and nowhere near the cost of widespread and dynamically occuring issues like https://github.com/pymc-devs/pymc3/issues/4240, which&mdash;by the way&mdash;we had to deal with while working on `pymc3-hmm`, because it actually affected _all_ custom `Distribution`s that didn't fit the low-level pretty printer's expectations.

If for some reason you believe a `try` block will solve all foreseeable problems, you're mistaken.  Consider, for instance, a seemingly clever developer who really tries to take this pretty printing thing to its logical conclusion and walks the `Variable`s' arguments. If they're not careful, they could easily bring simple string output for a large graph to a crawl, or&mdash;worse yet&mdash;their buggy implementation could lead to infinite recursions, forcing other hapless developers to wait until a silent `RecursionError` is raised.

You're noticeably downplaying the damage caused by bad `__[str|repr]__`s (especially ones that can be hot-swapped at any time) and playing up the extremely marginal benefits of this approach to pretty printing.

Does this mean we shouldn't try to make pretty printers?  Obviously not, but it does mean that we probably shouldn't substitute simple string printing with a haphazard approach to pretty printing. 

Keeping `__str__` and `__repr__` separate from the goals of pretty printing at least makes it possible to get a simple and consistent string representation for quick assessments during development and debugging.  Even fancy consoles like IPython that implement pretty printing generally won't take over the representation of objects in critical areas like a debugger.  Your proposed approach unfortunately does.

## Illustrations of this new feature

It appears as though you don't really understand how fundamentally limited this approach is, since you keep making statements implying that this PR and/or https://github.com/pymc-devs/pymc3/pull/4692 will add an unqualified level of console-agnostic pretty printing.  It won't, and, if you don't understand this, it's likely that anyone else following this discussion wouldn't either, so I'll try to illustrate.

In the following, I'll reproduce the exact intended use of these changes:
```python
import aesara
import aesara.tensor as at

from aesara.graph.basic import Variable



x = at.vector("x")

x._str_impl = lambda: "my custom __str__"

str(x)
# 'my custom __str__'
```

First off, we can't easily get information about the object we're customizing unless we use the unnecessarily cumbersome `types.MethodType` approach.  This is the first, and simplest, basic design flaw.


Let's say we only wanted to extend the existing `__str__` output of `x`:
```python
import types


x._str_impl = types.MethodType(lambda self: f"my custom {self}", x)


str(x)

# RecursionError: maximum recursion depth exceeded while calling a Python object
```


Uh oh; if this were used in https://github.com/pymc-devs/pymc3/pull/4692, here's where that silently caught `RecursionError` would noticeably slow down `str` output.  Looks like we need to be more careful about recursion, especially if we intend to use an object's existing `__str__`.

In a standard `__[str|repr]__` implementation this recursion would&mdash;hopefully&mdash;be much more apparent, but, in this context, there's a greater chance of it being masked by the unnecessary indirection, especially when an implementation is less trivial than this example.

Anyway, it seems like we only need to use the base class's `_repr_impl`:
```python
def my_str_impl(self):
    base_str = super()._str_impl()
    return f"my custom {base_str}"


x._str_impl = types.MethodType(my_str_impl, x)


str(x)
# RuntimeError: super(): __class__ cell not found
```

Nope; looks like we can't use the normal means of accessing base class implementations.  (Again, this would be a silent error in https://github.com/pymc-devs/pymc3/pull/4692.)

Now, while this goal can be accomplished using the less than ideal `Variable._str_impl(self)`, this exercise has already demonstrated how our earlier concerns are not overly conservative, since the sheer awkwardness of this approach can easily lead to errors.

But there's more.

Let's get what we're looking for out of this implementation:
```python
def my_str_impl(self):
    base_str = Variable._str_impl(self)
    return f"my custom {base_str}"


x._str_impl = types.MethodType(my_str_impl, x)


str(x)
# 'my custom x'
```

Now, let's see how well this pretty printing works:
```python
y = x * 2

str(y)
# 'Elemwise{mul,no_inplace}.0'
```

Clearly this pretty printing doesn't work at all if we don't apply it directly to each and every variable instance. That seems **considerably** more limited than `reprlib`, `pprint`, `IPython.lib.pretty`, `aesara.printing`, etc. All of the alternatives I provided can be made to work on _all_ `Variable` instances, so I think that's a major shortcoming of your previous considerations.

Let's try some pretty printing that does work for _all_ variables:
```python
x = at.vector()

x._str_impl = types.MethodType(lambda self: "this is a vector", x)

y = at.broadcast_to(x, (1, 2))

aesara.dprint(y)
# BroadcastTo [id A] ''
#  |this is a vector [id B]
#  |Subtensor{int64} [id C] ''
#  | |TensorConstant{[1 2]} [id D]
#  | |ScalarConstant{0} [id E]
#  |Subtensor{int64} [id F] ''
#    |TensorConstant{[1 2]} [id D]
#    |ScalarConstant{1} [id G]
```

Agh; looks like we've ruined the useful debug output of `aesara.dprint`, because now we can't tell which `Type` the pretty printed variable is.  Anyone debugging these altered `__str__`s will simply have to hope that the new `__str__` is at least as informative as the ones they're expecting.


Let's try a more motivating example:
```python
from aesara.tensor.random.basic import normal


x = normal(size=10)

def my_str_impl(self):
    return f"Normal({x.owner.inputs[3]}, {x.owner.inputs[4]}, {x.owner.inputs[1]})"


x._str_impl = types.MethodType(my_str_impl, x)

str(x)
# 'Normal(TensorConstant{0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 10})'
```

That's more like it!  Now, let's make use of our new pretty printing, and transform this variable and observe the result in its more convenient pretty printed form:
```python
from aesara.tensor.random.opt import lift_rv_shapes


new_x = lift_rv_shapes(x.owner).outputs[1]

str(new_x)
# 'normal_rv.out'
```

Looks like we've lost the pretty printing again.

Let's try this with the other most common variable type:
```python
x = at.as_tensor([1, 2])


def my_str_impl(self):
    return f"{x.data}"

x._str_impl = types.MethodType(my_str_impl, x)


str(x)
# 'TensorConstant{[1 2]}'
```

No go.  Looks like we'll need to add this indirection "feature" to more classes in order to get reasonable pretty printing coverage.

In conclusion, the capabilities these changes provide are not even close to being on par with the alternatives, and the [...]

2021-05-20 08:23 UTC, Spaak commented
@brandonwillard 

To avoid any misunderstanding: I don't have a particular personal emotional attachment to my proposed route of implementation here.

> you're not actually weighing the pros and cons of the specific approach endorsed by these changes.

> consider *actually* assessing these alternative approaches that are notably better for both your goals and this project.

> they're just going to be dismissed in favor of vague pleas

Assessing the pros and cons is what I thought we were doing, and I don't think I dismissed any of your points (i.e., the reason for the `_str_impl` idea is that you convincingly argued that patching `__class__` was risky.) Reaching a different conclusion in a deliberation does not mean that there was no deliberation at all. For what it's worth: I again think you raise valid points, especially considering debug printing.

2021-05-20 08:23 UTC, closed without merging